name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.x'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Go Vet
      run: go vet ./...
      
    - name: Go Fmt Check
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "Go code is not properly formatted:"
          gofmt -d .
          exit 1
        fi 